force-apps/HOW/main/default/objects/Contact/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/HOW/main/default/objects/Contact/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-apps/HOW/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <displayFormat>FAMILY-{0000}</displayFormat>
        <label>Family Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/HOW/main/default/objects/Family__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-apps/HOW/main/default/classes/TestFamilyLastNames.cls
@IsTest
public class TestFamilyLastNames {
	@TestSetup
	public static void testSetup() {
		createContacts(new List<String>{ 'LN1', 'LN2' }, 0, 2);
	}

	@IsTest
	public static void newContacts_WithDifferent_ExistingLastNames() {
		createContacts(new List<String>{ 'LN1', 'LN2' }, 2, 2);
	}

	@IsTest
	public static void newContacts_WithDuplicate_ExistingLastNames() {
		createContacts(new List<String>{ 'LN1', 'LN1' }, 2, 2);
	}

	@IsTest
	public static void newContacts_WithDifferent_NewLastNames() {
		createContacts(new List<String>{ 'LN3', 'LN4' }, 2, 4);
	}

	@IsTest
	public static void newContacts_WithDuplicate_NewLastNames() {
		createContacts(new List<String>{ 'LN3', 'LN3' }, 2, 3);
	}

	@IsTest
	public static void updateContacts_ExistingLastName() {
		updateContacts('LN1', 'LN2');
	}

	@IsTest
	public static void updateContacts_NewLastName() {
		updateContacts('LN1', 'LN3');
	}

	@IsTest
	public static void updateContacts_NoChange() {
		updateContacts('LN1', 'LN1');
	}


	private static void createContacts(List<String> lastNames, Integer expectedBefore, Integer expectedAfter) {
		Id recTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Family').getRecordTypeId();
		List<Family__c> families = [SELECT Id FROM Family__c];
		System.assertEquals(expectedBefore, families.size());
		List<Contact> contacts = new List<Contact>();
		for (String lastName : lastNames) {
			contacts.add(new Contact(LastName = lastName, RecordTypeId = recTypeId));
		}
		insert contacts;
		for (Contact c : [SELECT Id, LastName, Family__r.LastName__c FROM Contact]) {
			System.assertEquals(c.LastName, c.Family__r.LastName__c);
		}
		families = [SELECT Id FROM Family__c];
		System.assertEquals(expectedAfter, families.size());
	}

	private static void updateContacts(String oldLastName, String newLastName) {
		Contact oldContact = [SELECT Id FROM Contact WHERE LastName = :oldLastName];
		oldContact.LastName = newLastName;
		update oldContact;
		for (Contact newContact : [SELECT Id, LastName, Family__r.LastName__c FROM Contact WHERE Id = :oldContact.Id]) {
			System.assertEquals(newLastName, newContact.LastName);
			System.assertEquals(newContact.LastName, newContact.Family__r.LastName__c);
		}
	}
}