force-apps/HOW/main/default/objects/Contact/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/HOW/main/default/objects/Contact/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-apps/HOW/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <displayFormat>FAMILY-{0000}</displayFormat>
        <label>Family Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/HOW/main/default/classes/EX03AE_Response.cls
public class EX03AE_Response {
	@AuraEnabled
	public List<EX03AE_FamilyWithContacts> familiesWithContacts { get; set; }
	@AuraEnabled
	public integer theAnswer {
		get {
			return 42;
		}
		private set;
	}

	public EX03AE_Response() {
		this.familiesWithContacts = new List<EX03AE_FamilyWithContacts>();
	}

	public void add(Family__c family) {
		EX03AE_FamilyWithContacts familyWithContacts = new EX03AE_FamilyWithContacts();
		familyWithContacts.family = family;
		familyWithContacts.contacts = family.Contacts__r;
		familyWithContacts.contactsCount = family.Contacts__r.size();
		this.familiesWithContacts.add(familyWithContacts);
	}
}