force-apps/HOW/main/default/objects/Contact/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/HOW/main/default/objects/Contact/fields/FamilyLastName__c.field-meta.xml
<CustomField>
    <fullName>FamilyLastName__c</fullName>
    <formula>Family__r.LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Family&apos;s Last Name</label>
    <type>Text</type>
</CustomField>

force-apps/HOW/main/default/objects/Contact/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-apps/HOW/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <displayFormat>FAMILY-{0000}</displayFormat>
        <label>Family Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/HOW/main/default/objects/Family__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-apps/HOW/main/default/classes/EX03_QueryFamilies.cls
public with sharing class EX03_QueryFamilies {
	@InvocableMethod(label='Get Families' description='Demonstrates calling Apex to get data' category='Contact')
	public static List<FamilyResponse> getFamilies(List<FamilyRequest> familyRequests) {
		// Initalize response
		List<FamilyResponse> output = new List<FamilyResponse>();
		EX03AE_Response aeResponse = new EX03AE_Response();
		FamilyResponse familyResponse = new FamilyResponse();
		familyResponse.response = aeResponse;
		output.add(familyResponse);

		System.assertEquals(1, familyRequests.size());
		FamilyRequest familyRequest = familyRequests[0];
		for (Family__c family : [
			SELECT Id, LastName__c, (SELECT Id, FirstName, LastName, FamilyLastName__c FROM Contacts__r ORDER BY FirstName)
			FROM Family__c
			WHERE Id IN :familyRequest.Families
			ORDER BY LastName__c
			LIMIT :familyRequest.maxFamilies
		]) {
			aeResponse.add(family);
		}

		return output;
	}

	public class FamilyRequest {
		@InvocableVariable(label='Families input' description='Family records without related contacts' required=true)
		public List<Family__c> families;
		@InvocableVariable(label='Max families' description='How many family records do you want back?')
		public Integer maxFamilies;
	}

	public class FamilyResponse {
		@InvocableVariable(label='Families output' description='Family records with related contacts')
		public EX03AE_Response response;
	}
}