force-apps/HOW/main/default/objects/Contact/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/HOW/main/default/objects/Contact/recordTypes/Family.recordType-meta.xml
<RecordType>
    <fullName>Family</fullName>
    <active>true</active>
    <label>Family</label>
</RecordType>

force-apps/HOW/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <displayFormat>FAMILY-{0000}</displayFormat>
        <label>Family Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/HOW/main/default/objects/Family__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-apps/HOW/main/default/classes/EX02_LinkFamily.cls
public without sharing class EX02_LinkFamily {
	@InvocableMethod(label='Link Families' description='Associates a contact with the corresponding family based on the last name' category='Contact')
	public static List<Contact> linkFamily(List<Contact> contacts) {
		Set<String> lastNames = new Set<String>();
		Map<String, Family__c> mapFamiliesByLastName = new Map<String, Family__c>();

		// Find contact last names
		for (Contact contact : contacts) {
			lastNames.add(contact.LastName);
			mapFamiliesByLastName.put(contact.LastName, null);
		}

		// Find existing families
		for (Family__c family : [SELECT Id, LastName__c FROM Family__c WHERE LastName__c IN :lastNames]) {
			mapFamiliesByLastName.put(family.LastName__c, family);
		}

		// Create missing families (last names without a family record)
		List<family__c> newFamilies = new List<Family__c>();
		for (String lastName : mapFamiliesByLastName.keyset()) {
			if (mapFamiliesByLastName.get(lastName) == null) {
				newFamilies.add(new Family__c(LastName__c = lastName));
			}
		}
		insert newFamilies;

		// Add new families to the map
		for (Family__c family : newFamilies) {
			mapFamiliesByLastName.put(family.LastName__c, family);
		}

		// Update contacts
		for (Contact contact : contacts) {
			contact.Family__c = mapFamiliesByLastName.get(contact.LastName).Id;
		}

		// We could do the DML here, but do it in flow in case something else needs to be updated
		// update contacts;

		return contacts;
	}
}